server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:4406/game?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  webflux:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    cache: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false